# fly.toml app configuration file generated for mrwinrock-api on 2025-08-10T15:12:10+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mrwinrock-api'
primary_region = 'sin'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  auto_start_machines = true
  auto_stop_machines = true
  force_https = true
  internal_port = 8080
  min_machines_running = 0

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "512mb"
